### ISSUE TITLE
Documentation for time series plot creation is out-of-date

### ISSUE THREAD

**Issue by ElizabethRoseStarling** [cms-gem-daq-project/gem-plotting-tools#130]
Out of date documentation as seen here: https://github.com/cms-gem-daq-project/gem-plotting-tools#full-example-for-p5-s-curve-data

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Current Behavior

Documentation still references git-based commands, such as "vi $GEM_PLOTTING_PROJECT/mapping/chamberInfo.py", which are no longer in use. This does not make it clear which copy of chamberInfo.py the user should change.

## Expected Behavior

Documentation should reference paths within venv, and make it clear that the files to be used/changed should be within the user's virtual environment, i.e. "vi /path/to/your/venv/slc6/py2.7/lib/python2.7/site-packages/gempython/gemplotting/mapping/chamberInfo.py"

**Comment by lmoureaux** [comment]
Thank you for taking the time to write a bug report.
