### ISSUE TITLE
Bug Report: plotTimeSeries.py --endDate Option Doesn't Work

### ISSUE THREAD

**Issue by ReyerBand** [cms-gem-daq-project/gem-plotting-tools#144]
## Brief summary of issue

When calling plotTimeSeries.py with the --endDate option, the script still creates a list with scan dates up to the current time.
### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Calling plotTimeSeries.py with --startDate=(time_1) and --endDate=(time_2) should generate a list of scans between the two specified date.
## Current Behavior

Calling plotTimeSeries.py with --startDate=(time_1) and --endDate=(time_2) gives a list of scan dates between time_1 and the current date.
### Steps to Reproduce (for bugs)

1. Call sudo -u gempro -i plotTimeSeries.py --listOfScanDatesOnly --startDate=2018.07.13 --endDate=2018.07.24 (for example) 
2. Read the output listOfScanDates.txt file in the /gemdata/GEMINIXXLY/scurve area
3. Last date in the list will be after the specified end date
4.

## Your Environment

* Version used:
* Shell used:

**Comment by bdorney** [comment]
Solved by #146
