### ISSUE TITLE
Bug report: error while analysing sbitThreshold scan with anaSBitThresh.py

### ISSUE THREAD

**Issue by giovanni-mocellin** [cms-gem-daq-project/gem-plotting-tools#224]
## Brief summary of issue
Not able to analyse the sbitThreshold scan, because python script for the analysis gives an error.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

It should run normally and analyse the sbitThreshold scan

## Current Behavior

anaSBitThresh.py /data/bigdisk/GEM-Data-Taking/GE11_QC8///sbitRate/channelOR//2019.06.23.18.33/SBitRateData.root 
Loading info from input TTree
Traceback (most recent call last):
  File "/opt/cmsgemos/bin/anaSBitThresh.py", line 98, in <module>
    scandate = scandate)
  File "/usr/lib/python2.7/site-packages/gempython/gemplotting/utils/anautilities.py", line 1465, in sbitRateAnalysis
    list_bNames.remove('vfatID')
ValueError: list.remove(x): x not in list

### Steps to Reproduce (for bugs)

1. Login to the DAQ machine.
2. Run: anaSBitThresh.py /data/bigdisk/GEM-Data-Taking/GE11_QC8///sbitRate/channelOR//2019.06.23.18.33/SBitRateData.root
3. Get error as above
4.

## Context (for feature requests)

Analyse sbitThreshold scan, which needs to be done to properly configure the detectors before the data taking.

## Your Environment

DAQ machine

**Comment by bdorney** [comment]
Issue related to patch on the DAQ machine; patch has been reverted.  Closing as resolved.
