### ISSUE TITLE
NameError in calibrateThrDac.py

### ISSUE THREAD

**Issue by AndrewLevin** [cms-gem-daq-project/gem-plotting-tools#236]
`NameError` is thrown when I run `calibrateThrDac.py`

## Brief summary of issue
The variable `filePath` in this line

https://github.com/cms-gem-daq-project/gem-plotting-tools/blob/develop/macros/calibrateThrDac.py#L134

is not defined. I am not sure what this is supposed to do or whether it is needed.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

### Steps to Reproduce (for bugs)
I encountered this problem when running `calibrateThrDac.py` in my virtual environment on gem904daq01

## Context
Since this happens after the script finished, it doesn't really prevent me from doing anything, but it is still a runtime crash.

**Comment by bdorney** [comment]
good catch; change `filePath` to `outputDir`.
