### ISSUE TITLE
Feature Request: Summary Plot from anaUltraLatency.py

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/gem-plotting-tools#8]
Right now anaUltraLatency.py plots the data as 24 different plots instead of a single summary plot.

This makes it hard for the DOC or analyst to upload the data to the E-Log for an "at-a-glance" view.

Request this script makes a summary plot.

**Comment by mexanick** [comment]
I have requested modification provided by Alice Magnani. I'll prepare a PR

**Comment by bdorney** [comment]
@mexanick PR #7 has been merged in, I think it would be best if I close this issue and we make a new issue/feature request to include the feedback/modification you mentioned from Alice.

Please advise.

**Comment by bdorney** [comment]
Closing issue as no longer appears relevant and functionality implemented in merged PR.
