### ISSUE TITLE
Docs migration

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/gem-plotting-tools#94]
## Brief summary of issue
Current README needs to be refactored into a proper `docs` style
README should have info about getting set up, links to contributing guidelines, links to full documentation

### Types of issue
- [x] Cleanup

## Possible Solution (for bugs)
* Create `docs` folder
* Migrate documentation portion of README into this, preferably using rst for compatibility with `sphinx`/`readthedocs` style documentation

**Comment by mexanick** [comment]
Yes, let's use sphinx as a baseline. I'll look into sphinx setup for the reg_utils repo and will provide more detailed feedback and maybe a sort of template here as well. Basically, sphinx is using the ReStructured Text as doc format which is reasonably close to Markdown used in the existing readme, so it would not be a hard task to get the proper documentation with it. We will need a skeleton first and then distribute the existing content around it. Given the completeness of this project documentation in a README, I do not expect a need to write a lot of new stuff. 
After this is done and RPM installation procedure is polished, the README should shrink to a short instruction on getting the code installed and link to the full documentation as @jsturdy suggested.

**Comment by bdorney** [comment]
Was this resolved by #115 and #116?  Or is something more needed?

**Comment by lmoureaux** [comment]
> Was this resolved by #115 and #116? Or is something more needed?

A significant part of the README and many docstrings still have to be ported to `rst`

**Comment by bdorney** [comment]
Okay, thanks for update.  We keep this issue open for now.
